version: '3.7'

# from https://www.dabbleofdevops.com/blog/setup-a-mysql-python-docker-dev-stack
# docker-compose build; docker-compose up -d

services:
  db:
    image: mysql:5.7
    restart: always
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: njtransit
      MYSQL_DATABASE: buses_nj
      MYSQL_USER: njbuswatcher
      MYSQL_PASSWORD: njtransit
      TZ: America/New_York
    volumes:
      - bus_database:/var/lib/mysql

  acquire:
    restart: always
    build:
      context: .
      dockerfile: build/acquire/Dockerfile
    depends_on:
      - db
    volumes:
      # - bus_files:/app/data# mapped to volume
      - ./data:/app/data # mapped to host dir
      - bus_assets:/app/assets
    command:
      # tail -f /dev/null # use to start an exploding container and exec in
      /usr/local/bin/python3 /app/acquire.py

  api:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
    command:
      uvicorn api:app --host 0.0.0.0 --port 8080


  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    restart: unless-stopped
    ports:
      - 80:8501
    command:
      streamlit run app.py
      # tail -f /dev/null # use to start an exploding container and exec in


volumes:
  bus_database:
  bus_assets:
