version: '3.7'

# from https://www.dabbleofdevops.com/blog/setup-a-mysql-python-docker-dev-stack
# docker-compose build; docker-compose up -d

services:
  # todo, how to add indexes automatically at creation
  db:
    image: mysql:5.7
    restart: always
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: njtransit
      MYSQL_DATABASE: buses_nj
      MYSQL_USER: njbuswatcher
      MYSQL_PASSWORD: njtransit
      TZ: America/New_York
    volumes:
      - bus_database:/var/lib/mysql

  grabber:
    restart: always
    build:
      context: .
    depends_on:
      - db
    volumes:
      - bus_files:/app/data
      - bus_assets:/app/assets
    command:
      # tail -f /dev/null
      /opt/conda/envs/njbuswatcher/bin/python3 /app/acquire.py


  api:
    restart: always
    build:
      context: .
    volumes:
      - bus_assets:/app/assets
    # todo traefik — api at /api
    ports:
      - 80:5000
    environment:
      - FLASK_APP=/app/api.py
    command: flask run --host=0.0.0.0 --port=5000
    # command: gunicorn -w 1 -b :8000 app:server #todo change this for deployment
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

# traefik:
#   todo install traefik

#  map:
#    todo traefik - react-bootstrap app at /
#

#  app:
#    todo traefik - streamlit app at /dash


# todo add with the dyndns.env from ~/deployments/gandi-livedns
# todo stop the other gandi-livedns stack
#services:
#  dyndns:
#    image: jbbodart/gandi-livedns
#    restart: unless-stopped
#    env_file:
#      - "dyndns.env"
#

volumes:
  bus_database:
  bus_files:
  bus_assets:
