version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    init: true
    volumes:
      # Use a named volume for the source code
      - my-app:/workspace
      # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions
      # And/or for VS Code Insiders
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

    container_name: my-app-development
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  my-app:
  vscode-extensions:
  vscode-extensions-insiders:

# This external network is shared with the main docker-compose.yml config
# Ensures that services started from inside this dev container can all communicate
networks:
  my-app-network:
    external: true
